package com.mainiway.bean.po;

import com.mainiway.common.base.BaseBeanEntry;

/**
 * Model class of 图表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Chart extends BaseBeanEntry {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 图标名称. */
	private String name;

	/** value. */
	private String value;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
