package com.mainiway.bean.po;

import com.mainiway.common.base.BaseEntry;

/**
 * Model class of 工作流基础信息.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class WorkflowInfo extends BaseEntry {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** name. */
	private String name;

	/** 供应商. */
	private String vendor;

	/** 审查. */
	private String audit;

	/** 描述. */
	private String description;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVendor() {
		return vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	public String getAudit() {
		return audit;
	}

	public void setAudit(String audit) {
		this.audit = audit;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
