package com.mainiway.bean.po;

import com.mainiway.common.base.BaseBeanEntry;

/**
 * Model class of 工作流流程.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class WorkflowOrder extends BaseBeanEntry {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 工作流详情id. */
	private String workflowId;

	/** 序号. */
	private Integer num;

	/** 服务id. */
	private String serviceId;

	/** 描述. */
	private String description;

	public String getWorkflowId() {
		return workflowId;
	}

	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	public String getServiceId() {
		return serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
